=== rmmateosv/LM2324/examenU6/viajes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mayorista">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nombre" type="xs:string"/>
				<xs:element name="direccion" type="tipoDir"/>
				<xs:element name="telefono" type="tipoTel"/>
				<xs:element name="viaje" type="tipoViaje" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="tipoDir">
		<xs:restriction base="xs:string">
			<xs:maxLength value="100"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoTel">
		<xs:restriction base="xs:string">
			<xs:pattern value="\+[0-9]{2} [0-9]{3}\-[0-9]{3}\-[0-9]{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="tipoViaje">
		<xs:sequence>
			<xs:element name="destinos">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="destino" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="ciudad" type="xs:string" use="required"/>
								<xs:attribute name="pais" type="xs:string" use="required"/>
								<xs:attribute name="continente" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="precio">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:float">
							<xs:attribute name="moneda" type="xs:string" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="duracion" type="xs:string"/>
			<xs:element name="visitas">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="visita" type="xs:string" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="alojamiento">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="hotel" type="tipoHotel" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="oferta" minOccurs="0">
				<xs:complexType>
					<xs:choice>
						<xs:element name="descuento" type="xs:string"/>
						<xs:element name="bono" type="xs:string"/>
					</xs:choice>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="codigo" type="xs:ID" use="required"/>
		<xs:attribute name="fechaInicio" type="xs:date" use="optional"/>
		<xs:attribute name="fechaFin" type="xs:date" use="optional"/>
	</xs:complexType>
	<xs:complexType name="tipoHotel">
		<xs:all>
			<xs:element name="categoria">
				<xs:complexType>
					<xs:attribute name="estrellas" type="tipoCat" use="optional"/>
					<xs:attribute name="llaves" type="tipoCat" use="optional"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="direccion" type="tipoDir"/>
			<xs:element name="web" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="url" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="nombre" type="xs:string" use="required"/>
		<xs:attribute name="regimen" type="tipoR" use="optional"/>
	</xs:complexType>
	<xs:simpleType name="tipoCat">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="5"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoR">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PC"/>
			<xs:enumeration value="MP"/>
			<xs:enumeration value="AD"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== rmmateosv/LM2324/examenU6/viajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<mayorista xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="viajes.xsd" >
	<nombre>MoonTours</nombre>
	<direccion>Calle Falsa 123, Ciudad, País </direccion>
	<telefono>+34 123-456-789</telefono>
	<viaje codigo="V12345" fechaInicio="2024-05-01" fechaFin="2024-09-30">
		<destinos>
			<destino ciudad="París" pais="Francia" continente="Europa" />
			<destino ciudad="Roma" pais="Italia" continente="Europa" />
		</destinos>
		<precio moneda="EUR">1200.00</precio>
		<duracion>7 días</duracion>
		<visitas>
			<visita>Visita Torre Eiffel.</visita>
			<visita>Visita al Coliseo y al Foro Romano.</visita>
			<visita>Excursión a la Ciudad del Vaticano.</visita>
		</visitas>
		<alojamiento>
			<hotel nombre="Hotel Notre Dame">
				<categoria estrellas="3"/>
				<direccion>187 Pl. Jean-Paul II, 75004 Paris, Francia</direccion>
			</hotel>
			<hotel nombre="Hotel Roma" regimen="PC">
				<direccion>Via Nazionale 22, Roma, Italia</direccion>
				<categoria estrellas="4"/>
				<web url="http://wwww.hotelRoma.it"/>
			</hotel>
		</alojamiento>
		<oferta>
			<descuento> 20% al contratar antes del 31 de Mayo de 2024</descuento>
		</oferta>
	</viaje>
	<viaje codigo="V67890">
		<destinos>
			<destino ciudad="Nueva York" pais="Estados Unidos" continente="América" />
		</destinos>
		<precio moneda="USD">1500.00</precio>
		<duracion>5 días</duracion>
		<visitas>
			<visita>Visita a la Estatua de la Libertad y al Central Park.</visita>
			<visita>Paseo por Times Square y Broadway.</visita>
			<visita>Excursión al Museo Metropolitano de Arte.</visita>
		</visitas>
		<alojamiento>
			<hotel nombre="Hotel Manhattan"  regimen="AD">
				<direccion>123 5th Ave, Nueva York, Estados Unidos</direccion>
				<categoria estrellas="5"/>
			</hotel>
		</alojamiento>
		<oferta>
			<bono>Bebida incluída</bono>
		</oferta>
	</viaje>
	<viaje codigo="V34567">
		<destinos>
			<destino ciudad="Tokio" pais="Japón" continente="Asia" />
		</destinos>
		<precio moneda="JPY">200000.00</precio>
		<duracion>10 días</duracion>
		<visitas>
			<visita>Visita al Templo Senso-ji y al barrio de Asakusa.</visita>
			<visita>Paseo por el Parque Ueno y el Museo Nacional de Tokio.</visita>
			<visita>Excursión a la Torre de Tokio y al barrio de Shibuya.</visita>
			<visita>Visita a los jardines del Palacio Imperial.</visita>
		</visitas>
		<alojamiento>
			<hotel nombre="Apartamentos Tokyo" regimen="MP">
				<direccion>1 Chome-1-1 Oshiage, Tokio, Japón</direccion>
				<web url="http://wwww.TokyoApartments.com"/>
				<categoria llaves="3"/>
			</hotel>
		</alojamiento>
	</viaje>
	<viaje codigo="V456765" fechaInicio="2024-06-01" fechaFin="2024-09-30">
		<destinos>
			<destino ciudad="Oslo" pais="Noruega" continente="Europa" />
		</destinos>
		<precio moneda="EUR">2100.00</precio>
		<duracion>5 días</duracion>
		<visitas>
			<visita>Crucero Fiordos.</visita>
			<visita>Museo de los Barcos Vikingos.</visita>
		</visitas>
		<alojamiento>
			<hotel nombre="Hotel Central Square">
				<categoria estrellas="5"/>
				<direccion>Citybox Oslo, Prinsens gate 6, 0152 Oslo, Noruega</direccion>
				<web url="http://wwww.centralTour.com"/>
			</hotel>
		</alojamiento>
	</viaje>
</mayorista>
