=== rmmateosv/LM2324/u5/Schema/expediente.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="expediente">
		<xs:complexType>
			<xs:all>
				<xs:element name="nombre" type="xs:string"/>
				<xs:element name="apellidos" type="xs:string"/>
				<xs:element name="fecha_nacimiento" type="xs:date"/>
				<xs:element ref="matriculas"/>
				<xs:element name="contacto" type="tipoContacto"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="matriculas">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="matricula" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="curso" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="inicio" type="xs:date"/>
										<xs:element name="asignatura" minOccurs="0" maxOccurs="unbounded" type="tipoAsignatura"/>
										<xs:element name="fin" type="xs:date" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="curso" type="tipoCurso" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="ciclo" type="tipoCiclo" use="required"/>
						<xs:attribute name="titula" type="xs:boolean" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="tipoAsignatura">
		<xs:attribute name="nombre" type="xs:string" use="required"/>
		<xs:attribute name="nota" type="tipoNota" use="required"/>
		<xs:attribute name="convalidada" type="xs:boolean" use="optional"/>
	</xs:complexType>
	<xs:complexType name="tipoContacto">
		<xs:choice>
			<xs:element name="telefono">
				<xs:complexType>
					<xs:attribute name="numero" type="tipoTel" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="email">
				<xs:complexType>
					<xs:attribute name="email" type="tipoMail" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:simpleType name="tipoCiclo">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SMR"/>
			<xs:enumeration value="DAM"/>
			<xs:enumeration value="DAW"/>
			<xs:enumeration value="ASIR"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoNota">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="10"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoTel">
		<xs:restriction base="xs:int">
			<xs:totalDigits value="9"/>			
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoMail">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z0-9]+\@[a-zA-Z0-9]+\.[a-z]{2,3}"/>			
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoCurso">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="2"/>			
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== rmmateosv/LM2324/u5/Schema/expedienteJuan.xml
<?xml version="1.0" encoding="UTF-8"?>
<expediente xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="expediente.xsd">
	<nombre>Juan</nombre>
	<apellidos>García Pérez</apellidos>
	<fecha_nacimiento>1998-05-15</fecha_nacimiento>
	<matriculas>
		<matricula ciclo="DAM" titula="false">
		  <curso curso="1">
			<inicio>2022-09-01</inicio>
			<asignatura nombre="PRO" nota="8"/>
			<asignatura nombre="BD" nota="7"/>
			<asignatura nombre="LMSGI" nota="7"/>
			<asignatura nombre="SI" nota="7"/>
			<asignatura nombre="ED" nota="7"/>
			<asignatura nombre="FOL" nota="5" convalidada="true"/>
			<fin>2023-06-30</fin>
		  </curso>
		  <curso curso="2">
			<inicio>2023-09-01</inicio>
			<asignatura nombre="EIE" nota="5" convalidada="true"/>
		  </curso>
		</matricula>
		<matricula ciclo="ASIR" titula="true">
		  <curso curso="1">
			<inicio>2019-09-01</inicio>
			<asignatura nombre="ISO" nota="10"/>
			<asignatura nombre="PAR" nota="7"/>
			<asignatura nombre="LMSGI" nota="7"/>
			<asignatura nombre="FH" nota="7"/>
			<asignatura nombre="GBD" nota="7"/>
			<asignatura nombre="FOL" nota="7"/>
			<fin>2020-06-30</fin>
		  </curso>
		  <curso curso="2">
			<inicio>2020-09-01</inicio>
			<asignatura nombre="ASO" nota="10"/>
			<asignatura nombre="SAD" nota="10"/>
			<asignatura nombre="SRI" nota="10"/>
			<asignatura nombre="IAW" nota="10"/>
			<asignatura nombre="ASGBD" nota="10"/>
			<asignatura nombre="FCT" nota="10"/>
			<asignatura nombre="EIE" nota="10"/>
			<fin>2021-06-30</fin>
		  </curso>
		</matricula>
	</matriculas>
	<contacto>
		<telefono numero="611223344"/>
	</contacto>
</expediente>

=== rmmateosv/LM2324/u5/Schema/expedienteAna.xml
<?xml version="1.0" encoding="UTF-8"?>
<expediente  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="expediente.xsd">
	<matriculas>
		<matricula ciclo="DAM" titula="false">
		  <curso curso="1">
			<inicio>2022-09-01</inicio>
		  </curso>
		</matricula>
	</matriculas>
	<contacto>
		<email email="anals2000@gmail.com"/>
	</contacto>
	<nombre>Ana</nombre>
	<apellidos>López Sánchez</apellidos>
	<fecha_nacimiento>2000-10-11</fecha_nacimiento>
</expediente>
