=== rmmateosv/LM2324/u5/Schema/liga.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- Definición GLOBAL de elemento raíz -->
	<xs:element name="jornada">
		<!-- ELEMENTO COMPLEJO COMPUESTO -->
		<xs:complexType>
			<!-- DEFINICIÓN DE SECUENCIA DE ELEMENTOS -->
			<xs:sequence>
				<!-- LO DEFINIMOS DE FORMA LOCAL -->
				<xs:element name="numero" type="tipoNumLiga"/>
				<!-- Códigos y partidos los definimos de forma GLOBAL
				por legiilidad del código o posible reutilización -->
				<xs:element ref="codigos"/>
				<xs:element ref="partidos"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- Definición GLOBAL de códigos -->
	<xs:element name="codigos">
		<xs:complexType>
			<xs:sequence>
				<!-- Definición LOCAL de código -->
				<xs:element name="codigo" type="xs:IDREF" 
				minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="partidos">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="partido" minOccurs="1" 
				maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="fecha" type="xs:date"/>
							<xs:element name="hora" type="xs:time"/>
							<xs:element ref="estadio" minOccurs="0"/>
							<xs:element ref="equipos"/>
							<xs:element ref="acciones"/>
							<xs:element ref="resultado"/>							
						</xs:sequence>
						<xs:attribute name="codigo" type="xs:ID" use="required"/>
						<xs:attribute name="arbitros" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="estadio">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="miTexto20">
					<xs:attribute name="codigo" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="equipos">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="equipo" minOccurs="2" maxOccurs="2">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="jugadores"/>
							<xs:choice>
								<xs:element name="entrenador" type="xs:string"/>
								<xs:element name="segundo" type="xs:string"/>
							</xs:choice>
						</xs:sequence>
						<xs:attribute name="equipo" type="xs:ID" use="required"/>
						<xs:attribute name="tipo" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="jugadores">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="jugador" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="nombre" type="xs:string" use="required"/>
						<xs:attribute name="dorsal" type="xs:unsignedInt" use="required"/>
						<xs:attribute name="posicion" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="acciones">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="accion" maxOccurs="unbounded">
					<xs:complexType>
						<xs:all>
							<xs:element name="minuto" type="xs:int"/>
							<xs:element name="equipoA" type="xs:string"/>
							<xs:element name="jugadorA" type="xs:string"/>
						</xs:all>
						<xs:attribute name="tipo" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="resultado">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="finalizacion">
					<xs:complexType>
						<xs:attribute name="fecha" type="xs:date" use="required"/>
						<xs:attribute name="hora" type="tipoHora" use="required"/>
						<xs:attribute name="minuto" type="tipoMin" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="golesL" type="xs:int"/>
				<xs:element name="golesV" type="xs:int"/>
				<xs:element name="ganador" type="tipoGanador"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- Definimos un tipo que admita un número entero
		o un string-->	
	<xs:simpleType name="tipoNumLiga">
		<xs:union memberTypes="xs:int xs:string"/>
	</xs:simpleType>
	<!-- Definimos un tipo string que tenga mínimo 5
	caracteres y máximo 20 -->
	<xs:simpleType name="miTexto20">
		<xs:restriction base="xs:string">
			<xs:maxLength value="20"/>
			<xs:minLength value="5"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoHora">
		<xs:restriction base="xs:unsignedInt">
			<xs:minInclusive value="0"/>
			<xs:maxExclusive value="24"/>
			<!-- <xs:maxInclusive value="23"/> -->
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoMin">
		<xs:restriction base="xs:unsignedInt">
			<xs:minInclusive value="0"/>		
			<xs:maxInclusive value="59"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoGanador">
		<xs:restriction base="xs:string">
			<xs:enumeration value="L"/>
			<xs:enumeration value="V"/>
			<xs:enumeration value="E"/>
			<xs:enumeration value="l"/>
			<xs:enumeration value="v"/>
			<xs:enumeration value="e"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== rmmateosv/LM2324/u5/Schema/jornadaLiga.xml
<?xml version="1.0" encoding="UTF-8"?>
<jornada xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="liga.xsd">
	<numero>Primera</numero>
	<codigos>
		<codigo>j01-RM-Barcelona</codigo>
		<codigo>j01-ALTM-ALTB</codigo>
	</codigos>
	<partidos>
		<partido codigo="j01-RM-Barcelona" arbitros="Pepe Ana Juan Luisa">
			<fecha>2024-01-01</fecha>
			<hora>17:00:00</hora>
			<estadio codigo="BER">Bernabéu</estadio>
			<equipos>
				<equipo equipo="RM" tipo="L">
					<jugadores>
						<jugador nombre="Bellinghann" dorsal="5" posicion="centro"/>
						<jugador nombre="Vini" dorsal="7" posicion="delantero"/>
					</jugadores>
					<entrenador>Ancelotti</entrenador>
				</equipo>
				<equipo equipo="Barcelona" tipo="V"> 
					<jugadores>
						<jugador nombre="Gavi" dorsal="6" posicion="centro"/>
						<jugador nombre="pedri" dorsal="8" posicion="centro"/>
					</jugadores>
					<segundo>Óscar Hernández</segundo>
				</equipo>
			</equipos>
			<acciones>
				<accion tipo="Gol">
					<minuto>8</minuto>
					<equipoA>RM</equipoA>
					<jugadorA>5</jugadorA>
				</accion>
			</acciones>
			<resultado>
				<finalizacion fecha="2024-01-01" hora="19" minuto="45"/>
				<golesL>1</golesL>
				<golesV>0</golesV>
				<ganador>L</ganador>
			</resultado>
		</partido>
		<partido  codigo="j01-ALTM-ALTB"  arbitros="María Óscar Mario Lola">
			<fecha>2024-01-01</fecha>
			<hora>17:00:00</hora>
			<equipos>
				<equipo equipo="ALTM" tipo="L">
					<jugadores>
						<jugador nombre="Morata" dorsal="15" posicion="centro"/>
						<jugador nombre="Griezman" dorsal="17" posicion="delantero"/>
					</jugadores>
					<entrenador>Simeone</entrenador>
				</equipo>
				<equipo equipo="ALTB" tipo="V"> 
					<jugadores>
						<jugador nombre="I.William" dorsal="26" posicion="centro"/>
						<jugador nombre="N.William" dorsal="28" posicion="centro"/>
					</jugadores>
					<entrenador>Valverde</entrenador>
				</equipo>
			</equipos>
			<acciones>
				<accion tipo="Gol">
					<jugadorA>28</jugadorA>
					<equipoA>ALTB</equipoA>
					<minuto>18</minuto>
				</accion>
			</acciones>
			<resultado>
				<finalizacion fecha="2024-01-01" hora="09" minuto="30"/>
				<golesL>0</golesL>				
				<golesV>1</golesV>
				<ganador>V</ganador>
			</resultado>
		</partido>	
	</partidos>

</jornada>
