<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE partido[
<!ELEMENT partido (fecha,hora,equipos,acciones)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT equipos (equipo,equipo)>
<!ELEMENT equipo (jugadores)>
<!ATTLIST equipo equipo ID #REQUIRED tipo (L|V) #REQUIRED>
<!ELEMENT jugadores (jugador+)>
<!ELEMENT jugador EMPTY>
<!ATTLIST jugador nombre ID #REQUIRED dorsal CDATA #REQUIRED 
          posicion (portero|defensa|delantero|centro) #IMPLIED>
<!ELEMENT acciones (accion*)>
<!ELEMENT accion (minuto,equipo,jugador)> <!-- considereamos que puede haber un partido sin acciones -->		  
<!ATTLIST accion tipo (Gol|TR|TA|Panalti|FJ) #REQUIRED>
<!ELEMENT minuto (#PCDATA)>
<!ELEMENT equipo (#PCDATA)>
<!ELEMENT jugador (#PCDATA)>
]
>
<partido>
	<fecha>2024-01-01</fecha>
	<hora>17:00</hora>
	<equipos>
		<equipo equipo="RM" tipo="L">
			<jugadores>
				<jugador nombre="Bellinghann" dorsal="5" posicion="centro"/>
				<jugador nombre="Vini" dorsal="7" posicion="delantero"/>
				
			</jugadores>
		</equipo>
		
		<equipo equipo="Barcelona" tipo="V"> 
			<jugadores>
				<jugador nombre="Gavi" dorsal="6" posicion="centro"/>
				<jugador nombre="pedri" dorsal="8" posicion="centro"/>
			</jugadores>
		</equipo>
	</equipos>
	
	<acciones>
		<accion tipo="Gol">
			<minuto>8</minuto>
			<equipo>RM</equipo>
			<jugador>5</jugador>
		</accion>
	</acciones>
</partido>