=== rmmateosv/LM2324/u5/facturas.dtd
<!ELEMENT factura (cab,detalle,pagada?)>
<!ELEMENT cab (cliente,fecha,(telefono|email))>
<!ATTLIST cab numeroF id #REQUIRED>
<!ELEMENT cliente (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT articulo EMPTY>
<!ATTLIST articulo codigo CDATA #REQUIRED nombre CDATA #REQUIRED cantidad CDATA #REQUIRED precio CDATA #REQUIRED>
<!ELEMENT linea (articulo)>
<!ATTLIST linea id CDATA #REQUIRED>
<!ELEMENT facturas (factura+)>
<!ELEMENT detalle (linea+)>

=== rmmateosv/LM2324/u5/01facturas.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE facturas SYSTEM "facturas.dtd">
<facturas>
	<factura>
		<cab numeroF="1">
			<cliente>1111111A</cliente>
			<fecha>2024/02/28</fecha>
			<!-- elemento telfono o email -->
		</cab>
		<detalle>
			<linea id="1">
				<articulo codigo="A01" nombre="Ruedas Michelín" 
				cantidad="2" precio="80"/>
			</linea>
			<linea id="2">
				<articulo codigo="F02" nombre="Líquido de frenos" 
				cantidad="1" precio="15.8"/>
			</linea>
		</detalle>
		<pagada/> <!-- ELEMENTO OPCIONAL, SÓLO SI ESTÁ PAGADA -->
	</factura>
	<factura>
		<cab numeroF="2">
			<cliente>2222222B</cliente>
			<fecha>2022/03/28</fecha>
		</cab>
		<detalle>
			<linea id="1">
				<articulo codigo="A100" nombre="Filtro Aire" 
				cantidad="1" precio="15.34"/>
			</linea>
		</detalle>
	</factura>
</facturas>
